--
-- PostgreSQL database dump
--

\restrict AICL2XgpV4kmYMb4AlGXBJJGR5Nv50wz3hKCcWFgfh3mmn7Ailn3Lkv9FqgqtMl

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: product_categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.product_categories VALUES ('a4979ce1-ab6e-440d-84c4-02cfe26f8cdc', 'Analytical Instruments', 1, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_categories VALUES ('bb0eb73f-a2d5-4d0f-ab2c-c7eb18faae5b', 'Agro Management', 2, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_categories VALUES ('aa227ffd-f1ea-4f6f-b36a-96932c27d511', 'Consumables', 3, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_categories VALUES ('cb69be6a-8f1f-418f-a22e-11db85df6256', 'Nuclear Safety Devices', 4, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_categories VALUES ('6b5f4681-43fb-4209-8b99-f7aba1e69a0d', 'Gas Analyser', 5, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_categories VALUES ('4da8aa8c-0abd-471d-8a1f-06d9bf7d4df5', 'Meterology', 6, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_categories VALUES ('2a4bbf7a-0caf-46c1-a8be-cf170e9bfaa8', 'Semiconductor', 7, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_categories VALUES ('f9f32097-b6fc-4ef0-b787-1554c2119033', 'Bio-Medical', 8, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_categories VALUES ('57c661b5-f9b6-4b31-8781-3ab825b578dd', 'Industrial IoT & LoRa Systems', 9, '2026-06-04 00:00:00+05:30', '2026-06-04 00:00:00+05:30');
INSERT INTO public.product_categories VALUES ('b08bcaf5-ce11-4008-878e-22c0cae7f7a6', 'Agro IoT Sensors', 10, '2026-06-11 14:34:53.491861+05:30', '2026-06-11 14:34:53.491861+05:30');


--
-- Data for Name: product_providers; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.product_providers VALUES ('cb82337a-147d-4058-b196-24a79fe6a72d', 'Mass Spectrometry Instruments UK', 'https://www.massint.co.uk', 'UK', NULL, NULL, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_providers VALUES ('37e47288-8e54-45e1-a124-ec164e528149', 'SPIO Denmark', 'https://spiosystems.com', 'Denmark', NULL, NULL, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_providers VALUES ('9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', 'Spectrum Technologies USA', 'https://www.specmeters.com', 'USA', NULL, NULL, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_providers VALUES ('f4c88509-9b1a-43db-b4bd-9e66d79e7bd9', 'Alpha Resources USA', 'https://www.alpharesources.com', 'USA', NULL, NULL, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_providers VALUES ('5ec70178-f8f7-4907-8589-920a02877986', 'Nuvia France /Germany', 'https://www.nuvia.com', 'France', NULL, NULL, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_providers VALUES ('8f0b7473-a23d-430e-b5a7-76cfb0265826', 'Quantek USA', 'https://www.quantekinstruments.com', 'USA', NULL, NULL, '2026-02-12 22:43:59.002982+05:30', '2026-02-12 22:43:59.002982+05:30');
INSERT INTO public.product_providers VALUES ('579813e9-7436-4b71-b33d-3bfb1af42010', 'Spectrolytic GMBH', 'https://www.spectrolytic.com', 'Germany', NULL, NULL, '2026-02-12 22:43:59.002982+05:30', '2026-02-17 09:12:56.031374+05:30');
INSERT INTO public.product_providers VALUES ('159be580-ef48-4d94-baa6-ff94d2551648', 'Precision Glass Blowing USA', 'https://www.precisionglassblowing.com', 'USA', NULL, NULL, '2026-02-12 22:43:59.002982+05:30', '2026-02-17 09:12:56.031374+05:30');
INSERT INTO public.product_providers VALUES ('de3412dd-a9fe-4320-972a-0bfef08146a1', 'Lumasense USA/Germany', 'https://www.lumasenseinc.com', 'USA', NULL, NULL, '2026-02-17 09:12:56.031374+05:30', '2026-02-17 09:12:56.031374+05:30');
INSERT INTO public.product_providers VALUES ('5e6e4e79-4c1c-4818-9fc9-b3efafc681ae', 'Mahr Germany', 'https://www.mahr.com', 'Germany', NULL, NULL, '2026-02-12 22:43:59.002982+05:30', '2026-02-17 09:12:56.031374+05:30');
INSERT INTO public.product_providers VALUES ('74e49e04-6440-4538-957c-2a1272c7f511', 'ASTTC India', 'https://www.analyticasofttech.com/', 'India', NULL, NULL, '2026-02-12 22:43:59.002982+05:30', '2026-02-18 01:10:05.575874+05:30');


--
-- Data for Name: catalogue_products; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.catalogue_products VALUES ('0e7fc2cd-a3a4-4bff-b942-83f69becaf3c', 'Radioactivity & Environment Safety', 'Safety System', 'cb69be6a-8f1f-418f-a22e-11db85df6256', '5ec70178-f8f7-4907-8589-920a02877986', '/product_images/nuclear.jpg', '["/product_images/nuclear-nuvia.jpg"]', NULL, 'Comprehensive radioactive monitoring and environmental protection systems.', 'Nuvia provides comprehensive radioactive monitoring and environmental protection systems designed for nuclear power facilities, environmental monitoring stations, and emergency response applications.', '["Nuclear Power Plant Monitoring", "Environmental Radiation Monitoring", "Emergency Response", "Regulatory Compliance"]', '["Nuclear", "Government", "Environmental"]', '["Real-time radiation monitoring", "Environmental protection grade", "Multi-sensor network capability"]', '["Continuous monitoring system", "Regulatory compliance built-in", "Remote data access"]', '[]', 'Price on Request', 'INR', true, '2026-02-12 23:06:26.920767+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('29d8eb1e-1d96-4a61-977c-b0e161bfa0eb', 'CO2 Analyser', 'Gas Sensor', '6b5f4681-43fb-4209-8b99-f7aba1e69a0d', '8f0b7473-a23d-430e-b5a7-76cfb0265826', '/product_images/gas-co-2.webp', '["/product_images/gas-co-2-2.webp"]', NULL, 'Portable and benchtop CO2 analyzers for oxygen and headspace analysis.', 'Quantek analyzers provide fast, accurate, and easy to use CO2 and O2 measurement for Modified Atmosphere Packaging (MAP) and other gas analysis applications.', '["Food Package Testing", "Incubator Monitoring", "Controlled Atmosphere Storage"]', '["Food & Beverage", "Pharmaceutical", "Agriculture"]', '["Infrared NDIR sensor", "0.1% resolution", "Internal 12-hour battery"]', '["Large LED display", "Built-in sampling pump", "Rugged metal enclosure"]', '[]', 'Price on Request', 'INR', true, '2026-02-12 23:06:26.920767+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('ed2d88f9-d1d7-41b6-a6ae-8b1d893f6f4a', '3D Microscope', 'Measuring Microscope', '4da8aa8c-0abd-471d-8a1f-06d9bf7d4df5', '5e6e4e79-4c1c-4818-9fc9-b3efafc681ae', '/product_images/mahr-microscope-1.png', '["/product_images/mahr-microscope-2.png", "/product_images/mahr-micro-3.png"]', NULL, 'High-precision MarVision MM 500 measuring microscope with zoom lenses for the most minute components.', 'Mahr offers the new MarVision MM 500 measuring microscope for the workshop and laboratory in two versions, each with three measuring ranges: with manual axes or with CNC axis control. This means that a total of six models are available â€” choose the perfect solution for your requirements. The system features high-precision measurement of the most minute components using zoom lenses.', '["Micro-component Measurement", "Quality Assurance", "Dimensional Inspection", "Surface Topography"]', '["Precision Manufacturing", "Electronics", "Medical Devices", "Aerospace"]', '["Zoom lens technology for minute components", "Manual and CNC axis control options", "Three measuring ranges per version", "Six model configurations available"]', '["MarVision MM 500 platform", "Workshop and laboratory use", "Manual or CNC axis control", "High-precision zoom optics"]', '[]', 'Price on Request', 'INR', true, '2026-02-12 23:06:26.920767+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('51fce909-064c-49b4-959f-99de432c0ea0', 'GDMS Glove Adaptable Nuclear', 'Mass Spectrometer', 'a4979ce1-ab6e-440d-84c4-02cfe26f8cdc', 'cb82337a-147d-4058-b196-24a79fe6a72d', '/product_images/gdms-glove-box.jpg', '["/product_images/time-resolved-crater.png"]', NULL, 'Specially adapted GD-MS with front-end assembly designed for custom glove box fitting in nuclear applications.', 'The GDMS Glove Adaptable Nuclear is a variant of the GD90 Trace specifically engineered for nuclear glovebox environments. Its front end assembly allows for the fitting of a custom-designed glove box, enabling safe handling and analysis of radioactive and hazardous samples. It retains all the analytical capabilities of the standard GD90 â€” full elemental coverage from major to ultra-trace levels â€” while providing the containment and safety features required for nuclear fuel characterization and related applications.', '["Nuclear Fuel Characterization", "Hazardous Material Analysis", "Radioactive Sample Testing"]', '["Nuclear", "Defence", "Government Labs"]', '["Custom glove box front-end assembly", "Remote operation capability", "Radiation shielded components", "Same analytical performance as GD90 Trace"]', '["Safe handling of radioactive samples", "Full elemental coverage in containment", "USB interface with remote PC control"]', '[]', 'Price on Request', 'INR', true, '2026-02-12 23:06:26.920767+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('65399788-c25e-4578-911e-99ad5c65e606', 'Profilometer', 'Surface Profiler', '4da8aa8c-0abd-471d-8a1f-06d9bf7d4df5', '5e6e4e79-4c1c-4818-9fc9-b3efafc681ae', '/product_images/mahr-profilometer.png', '[]', NULL, 'Optical profilometers for two- and three-dimensional surface measurement and analysis â€” non-contact, material-independent and fast.', 'The MarSurf3D CP/CL select is Mahr''s established optical profilometry solution for Quality Assurance. These optical profilometers enable two- and three-dimensional measurement and analysis of surfaces â€” non-contact, independent of material, and fast. The system is ideal for workshop and laboratory environments where precise surface characterization is critical.', '["Surface Roughness QA", "Automotive Engine Parts", "Aerospace Components", "Medical Implants"]', '["Automotive", "Aerospace", "Medical Devices", "Precision Manufacturing"]', '["Optical non-contact measurement", "2D and 3D surface analysis", "Material-independent measurement", "High-speed data acquisition"]', '["MarSurf3D CP/CL select models", "Established QA-grade profilometry", "Non-contact operation \u2014 no sample damage", "Conforms to ISO/JIS standards"]', '[]', 'Price on Request', 'INR', true, '2026-02-12 22:43:59.002982+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('1f182607-d65a-462d-b8cd-9ee4d585fb4c', 'Weather Monitoring Station', 'Environmental Sensor', 'bb0eb73f-a2d5-4d0f-ab2c-c7eb18faae5b', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', '/product_images/lora-1.avif', '["/product_images/lora-2.avif", "/product_images/lora-3.avif"]', NULL, 'Complete weather monitoring solutions with wireless profilers and LoRa connectivity for precision agriculture.', 'Spectrum Technologies offers comprehensive weather monitoring solutions including profilers for weather stations and LoRa wireless profilers. These systems provide the accurate weather data needed for informed decision-making in precision agriculture, combined with soil measurement tools for a holistic farm management approach.', '["Crop Disease Forecasting", "Irrigation Scheduling", "Research Plots"]', '["Agriculture", "Environmental Science", "Research & Academia"]', '["LoRa wireless connectivity", "Integrated soil and weather profiling", "Solar powered option"]', '["Wireless cellular communication", "Easy installation", "Real-time alerts via app"]', '[]', 'Price on Request', 'INR', true, '2026-02-12 23:06:26.920767+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('abf8dc65-5527-480b-a186-ba57e24c46c1', 'Soil Moisture Analyser', 'Soil Sensor', 'bb0eb73f-a2d5-4d0f-ab2c-c7eb18faae5b', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', '/product_images/tdr-150.avif', '["/product_images/tdr-250.avif", "/product_images/tdr-350.avif"]', NULL, 'TDR soil moisture meters for precise measurement of soil moisture content critical for plant health.', 'Soil moisture plays a key role in the life of the plant. Nutrients in the soil solution provide the plant with the food it needs to grow. Water is also essential for regulating plant temperature through the process of transpiration. Plant root systems are better developed when growing in moist soil. Excessive levels of soil moisture can lead to anaerobic conditions that can promote the growth of plant and soil pathogens. Spectrum Technologies offers the FieldScout TDR series (TDR 150, TDR 250, TDR 350) for precise soil moisture measurement with various rod lengths and accessories including infrared temperature sensors.', '["Soil Moisture Monitoring", "Irrigation Scheduling", "Plant Disease Prevention", "Agricultural Research"]', '["Agriculture", "Environmental Science", "Research & Academia"]', '["Time Domain Reflectometry (TDR) technology", "Multiple rod length options (1.5\" to 8.0\")", "Infrared temperature sensor option", "Portable hand-held design"]', '["FieldScout TDR 150/250/350 models", "Carry case included with select models", "Pilot hole maker accessory", "Rod spacer for consistent measurements"]', '[]', 'Price on Request', 'INR', true, '2026-02-12 23:06:26.920767+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('7c559944-3479-45e7-b9bf-98c4001af97d', 'Real time IR Analyser', 'Mid-IR Analyzer', 'a4979ce1-ab6e-440d-84c4-02cfe26f8cdc', '579813e9-7436-4b71-b33d-3bfb1af42010', '/product_images/real-time-ir.jpg', '["/product_images/ir-types.jpg"]', NULL, 'Plug & play inline analyser for real-time, in-situ monitoring of oil and lubricant condition.', 'The FluidInspectIRÂ® is a series of plug & play inline analysers for the real-time, in-situ monitoring of oil and lubricant condition. They are fast becoming the system of choice for monitoring and protecting valuable plant assets in power generation such as engines, turbines and transformers, in metal-working plants like steel and aluminium, and with hydraulic, gear and other rotating equipment. The system provides the user with data 24/7 for key oil parameters relating to degradation, contamination, and additive depletion in the same format, units and accuracy as standard oil analysis laboratory reports. Available in multiple variants: PLUS and ULTRA for stationary assets, ATEX for offshore and hazardous environments, DEV for R&D, and MINI / MIRS-T-V for mobile vehicles.', '["In-service Oil Condition Monitoring", "Power Generation: Engines, Turbines, Transformers", "Hydraulic & Gear Equipment Monitoring", "Steel & Aluminium Plant Monitoring", "FAME Biodiesel Analysis", "Ethanol in Gasoline Testing"]', '["Power Generation", "Steel & Metals", "Oil & Gas", "Automotive", "Manufacturing"]', '["Mid-IR Spectroscopic measurement", "24/7 real-time data output", "Battery powered portable option", "No sample preparation required", "Results in conventional laboratory units", "ATEX variant for hazardous environments"]', '["Plug & play inline installation", "Multiple variants: PLUS, ULTRA, ATEX, DEV, MINI, MIRS-T-V", "Portable and benchtop configurations", "Significant cost savings on laboratory analysis", "Rugged and robust design"]', '[]', 'Price on Request', 'INR', true, '2026-02-12 22:43:59.002982+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('dbee3582-4015-4cd8-bcf4-daaae3ce1e8c', 'KSHAR-06 Conductivity/TDS Meter', 'Conductivity Meter', 'a4979ce1-ab6e-440d-84c4-02cfe26f8cdc', '74e49e04-6440-4538-957c-2a1272c7f511', '/product_images/conductivity-meter-asttc.png', '[]', NULL, 'High-accuracy combined meter for measuring Conductivity and Total Dissolved Solids in laboratory and field samples.', 'The KSHAR-06 is a versatile and robust instrument designed by ASTTC India for precise monitoring of water quality. It measures both Conductivity and Total Dissolved Solids (TDS) with exceptional accuracy across a wide range. Whether used in high-purity water systems or industrial effluent testing, the KSHAR-06 provides the critical data needed for ionic concentration analysis and environmental compliance.', '["Water Quality Monitoring", "Boiler & Cooling Tower Water Testing", "Industrial Effluent Analysis", "Agriculture & Hydroponics", "Reverse Osmosis (RO) System Testing"]', '["Manufacturing", "Environmental", "Agriculture", "Energy & Utilities", "Research & Academia"]', '["Conductivity Range: 0.01 \u00b5S/cm to 199.9 mS/cm", "TDS Range: 0.01 mg/L to 1999 mg/L", "Conductivity Accuracy: \u00b11.0% Full Scale @ 25\u00b0C", "Adjustable TDS conversion factor", "Built-in temperature compensation for high precision"]', '["Dual mode: Conductivity and TDS measurement", "Digital display with clear resolution", "Rugged construction for industrial environments", "Simple calibration procedure", "Compatible with standard conductivity cells"]', '[]', 'Price on Request', 'INR', true, '2026-02-18 00:46:10.53175+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('c14b4e7e-64e6-4b5b-bf66-83226d1aefda', 'CS-ONH Analyser & Consumables', 'Elemental Analyser', 'aa227ffd-f1ea-4f6f-b36a-96932c27d511', 'f4c88509-9b1a-43db-b4bd-9e66d79e7bd9', '/product_images/combustible-consumables.jpg', '["/product_images/eltra-header.jpg", "/product_images/tfs-icpmsheader.jpg"]', NULL, 'OEM-quality combustion consumable supplies and certified reference materials at below OEM prices.', 'Alpha Resources manufactures and sources the most comprehensive mix of consumables and certified reference materials offered by any aftermarket supplier in the combustion analysis marketplace. They offer combustion supplies compatible with major brands including Bruker, Costech, Elementar, ELTRA, C. Gerhardt, Horiba, LECO, and VELP. Additionally, Alpha Resources provides specialty reference materials standards, Optical Emission Spectroscopy supplies, metallography supplies, ICP-MS sample cones and skimmer cones, and sales & service for ELTRA analyzers. Their ISO 17025 lab regularly releases new certified reference materials.', '["Carbon/Sulfur Analysis", "Oxygen/Nitrogen/Hydrogen Analysis", "Organic Elemental Analysis", "Metallography & Surface Prep", "OES Spectroscopy"]', '["Steel & Metals", "Mining", "Petroleum & Fuels", "Quality Control Labs", "Research & Academia"]', '["Compatible with Bruker, ELTRA, LECO, Horiba, Elementar and more", "ISO 17025 certified laboratory", "Comprehensive CRM product line", "OEM-equivalent quality at competitive prices"]', '["Combustion consumable supplies (crucibles, boats, lids)", "Certified Reference Materials (metals, coal, coke, oils, fuels, soils)", "Optical Emission Spectroscopy supplies", "Metallography supplies (abrasives, polishing, mounting)", "ICP-MS sample and skimmer cones", "ELTRA analyzer sales & service (30+ years)"]', '[]', 'Price on Request', 'INR', true, '2026-02-12 23:06:26.920767+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('f5de8b8d-4826-4434-a4a8-836e63136388', 'GD-MS Glow Discharge Mass Spectrometer', 'Mass Spectrometer', 'a4979ce1-ab6e-440d-84c4-02cfe26f8cdc', 'cb82337a-147d-4058-b196-24a79fe6a72d', '/product_images/gdms-image.png', '["/product_images/conducting-samples.jpg", "/product_images/flat-samples.jpg", "/product_images/powder-samples.jpg"]', NULL, 'High resolution GD-MS for direct determination of elemental content from major (wt%) to ultra-trace (sub-ppb) within a single scan.', 'The GD90 Trace, the GDMS instrument from MSI, features a proven optical platform with innovative modern stable electronics and control. All voltages are under computer control providing unsurpassed ease of use with a simple USB interface to the control, acquisition and processing PC. Remote control of the instrument and hardware control of acquisition are also incorporated. It performs full elemental analysis of major (wt%) to ultra-trace elements (ppb to sub-ppb) within a single scan using direct solid sampling, alleviating the need for chemical digestion. MSI employs a team of highly skilled GDMS personnel with over 35 years of combined experience.', '["Metals & Alloys Purity", "Semiconductor Material Analysis", "Nuclear Fuel Characterization", "High Purity Materials Testing", "Depth-dependent distribution analysis in coatings", "Multi-layered advanced materials analysis"]', '["Nuclear", "Semiconductor", "Metals & Mining", "Aerospace", "Advanced Materials"]', '["Sub-ppb detection limits", "High resolution magnetic sector", "Continuously variable resolution from <400 to >10,000 RP", "Dual collectors with up to 12 orders of linear dynamic range", "Tantalum cell and source construction", "Cryo-cooling of GD cell to minimise gas backgrounds", "Low sputter rate: 150 nm/min (conductive), 100 nm/min (non-conductive)"]', '["Direct solids analysis \u2013 no chemical digestion needed", "Uniform sensitivity \u2013 no mass bias for light/heavy elements", "Minimal matrix effects using Relative Sensitivity Factors (RSF)", "Accommodates both pin and flat cell geometries", "Analyses conductive and non-conductive samples", "Custom-designed glove box fitting for nuclear applications", "USB interface with remote control capability"]', '[]', 'Price on Request', 'INR', true, '2026-02-12 22:43:59.002982+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('c07f5e82-b81f-4ff3-8660-6efaed87f98d', 'Soil Nutrient Analyser', 'Nutrient Meter', 'bb0eb73f-a2d5-4d0f-ab2c-c7eb18faae5b', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', '/product_images/ph-soil.avif', '["/product_images/ec-soil.avif", "/product_images/na-soil.avif", "/product_images/k-soil.avif", "/product_images/nitrate.avif", "/product_images/ca-soil.avif"]', NULL, 'Comprehensive soil nutrient analysis meters for measuring pH, EC, and specific ions like Nitrate, Potassium, Sodium, and Calcium.', 'Spectrum Technologies provides the LAQUA series of nutrient meters, essential for precise monitoring of soil health. These meters measure key plant nutrients and soil conditions including pH, Electrical Conductivity (EC), Sodium (Na+), Potassium (K+), Nitrate (NO3-), and Calcium (Ca2+). Measurement of these parameters is critical because, as Lord Kelvin stated, ''If you cannot measure it, you cannot improve it.'' These meters enable growers to optimize fertilizer application and ensure ideal growing conditions for plants through accurate monitoring of plant sap and soil solution nutrients.', '["Soil Health Assessment", "Fertilizer Management", "Hydroponic Nutrient Monitoring", "Irrigation Water Quality Testing", "Plant Tissue Sap Analysis"]', '["Agriculture", "Horticulture", "Research & Academia", "Environmental Science"]', '["LAQUA series pocket meters for precise ion measurement", "High-accuracy sensors for pH and EC", "Ion-selective electrodes for NO3-, K+, Na+, and Ca2+", "Quick calibration with specialized standard solutions", "Replaceable sensors for long-term reliability"]', '["Comprehensive NPK monitoring (Nitrate and Potassium)", "Soil pH and Electrical Conductivity (EC) testing", "Sodium (Na+) and Calcium (Ca2+) ion measurement", "Sampling sheets for small volume measurements", "Portable, waterproof pocket-sized design"]', '[]', 'Price on Request', 'INR', true, '2026-02-17 16:43:43.84796+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('ee7f85bb-3300-42b4-8cff-2db37ef6b9bb', 'ICPOES - ICPMS Components', 'Lab Supplies', 'aa227ffd-f1ea-4f6f-b36a-96932c27d511', '159be580-ef48-4d94-baa6-ff94d2551648', '/product_images/icp-consumables-1.webp', '["/product_images/icp-accessories.webp", "/product_images/icp-nebulizers.webp", "/product_images/icp-pumpimg-tube.webp"]', NULL, 'Precision ICP sample introduction consumables including torches, nebulizers, spray chambers, cones and RF coils.', 'Precision Glassblowing, based in Centennial, Colorado, USA, manufactures and supplies a comprehensive range of ICP sample introduction consumables. Their product portfolio includes cones (sample and skimmer), ICP accessories, nebulizers, pump tubing, RF coils, spray chambers and accessories, and torches and accessories. They also offer AA glassware, optical glass, custom glassware, laboratory glassware, custom glass coils, vapor and gas wavelength reference cells, and BEC-MOT cells. Services include machining, repairs and modifications, design and prototyping, and OEM manufacturing.', '["ICP-OES Analysis", "ICP-MS Analysis", "Atomic Absorption Spectroscopy", "Lab Equipment Maintenance"]', '["Analytical Laboratories", "Environmental Testing", "Pharmaceutical", "Research & Academia"]', '["Precision-manufactured ICP consumables", "Compatible with major ICP-MS brands", "Custom glassware design capability", "Certified quality standards"]', '["Torches & accessories", "Nebulizers", "Spray chambers & accessories", "Sample and skimmer cones", "RF coils", "Pump tubing", "AA and optical glassware", "Machining, repairs & OEM manufacturing services"]', '[]', 'Price on Request', 'INR', true, '2026-02-12 23:06:26.920767+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('50301fed-a5d3-49b4-bd5f-27b45d2e575d', 'Personal Radiation Monitoring Watch', 'Nuclear Safety Device', 'cb69be6a-8f1f-418f-a22e-11db85df6256', '74e49e04-6440-4538-957c-2a1272c7f511', '/product_images/rad-barc-watch.jpg', '["/product_images/barc-watch-2.jpeg"]', NULL, 'Wearable personal dosimeter watch for real-time radiation monitoring and personnel protection in hazardous environments.', 'ASTTC''s Personal Radiation Monitoring Watch is a cutting-edge wearable safety device designed for professionals working in nuclear facilities, medical imaging, and emergency response. It provides continuous, real-time tracking of radiation dose rates, acting as a personal lifeline against invisible hazards. With its compact watch form factor, it ensures that safety monitoring is effortless and always active, providing immediate alerts when safety thresholds are exceeded.', '["Personal Dose Monitoring", "Nuclear Power Plant Operations", "Medical & Industrial Radiography", "Emergency Response & First Responders", "Environmental Surveying"]', '["Nuclear", "Healthcare", "Defense", "Emergency Services", "Research & Academia"]', '["Real-time Gamma and X-ray dose rate measurement", "Cumulative dose tracking and storage", "Audible and visual vibration alarms", "High-sensitivity Geiger-Muller tube sensor", "Long-life rechargeable battery with USB charging"]', '["Compact, wearable watch design", "Easy-to-read LCD screen with backlight", "Adjustable alarm thresholds for safety", "Water-resistant and rugged for field use", "Internal memory for dose history logging"]', '[]', 'Price on Request', 'INR', true, '2026-02-18 00:46:10.53175+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('55263167-aff6-40d5-ae94-574f2603d023', 'HYDRON Series pH Meter', 'pH Meter', 'a4979ce1-ab6e-440d-84c4-02cfe26f8cdc', '74e49e04-6440-4538-957c-2a1272c7f511', '/product_images/ph-meter-hydron-8.jpg', '["/product_images/ph-hydron-7-front.jpg", "/product_images/ph-meter-hydron-7.jpg"]', NULL, 'Advanced laboratory pH meter series (HYDRON-07/09) for high-precision measurement of acidity and alkalinity.', 'The HYDRON series from ASTTC India offers professional-grade pH measurement solutions for research, quality control, and industrial laboratories. Featuring the HYDRON-07 and HYDRON-09 models, these instruments are designed for accuracy, reliability, and ease of use. They provide simultaneous display of pH and temperature, making them ideal for a wide range of analytical applications where precise chemical monitoring is essential.', '["Chemical Analysis & Research", "Quality Control in Manufacturing", "Water & Wastewater Testing", "Food & Beverage Industry", "Educational Laboratories"]', '["Pharmaceutical", "Chemical", "Environmental", "Food & Beverage", "Research & Academia"]', '["High resolution: 0.01 pH", "Simultaneous pH and temperature display", "Manual/Automatic Temperature Compensation", "Multi-point calibration with buffer recognition", "Large, backlit digital display"]', '["User-friendly interface with intuitive controls", "Durable electrode for long-term stability", "Compact benchtop design to save lab space", "Data hold and min/max recording functions", "Standard BNC connector for electrode compatibility"]', '[]', 'Price on Request', 'INR', true, '2026-02-18 00:46:10.53175+05:30', '2026-03-24 18:49:54.772492+05:30', false);
INSERT INTO public.catalogue_products VALUES ('55216678-65af-4dd0-a6c5-8bee857ddb2f', 'LoRa Tester', 'Industrial IoT & LoRa Systems', '57c661b5-f9b6-4b31-8781-3ab825b578dd', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', '/product_images/loratester.jpg', '[]', NULL, 'Solar-powered tool that maps LoRa signal coverage', 'A compact, solar-powered tool with an integrated GPS chip, LoRa radio that maps signal coverage by pressing a button to transmit your location to SpecConnect, a platform for monitoring and managing LoRa network data', '["Signal Mapping", "Network Testing"]', '["Telecommunications", "Agriculture"]', '["Integrated GPS chip for precise location tagging", "Built-in LoRa radio for signal transmission", "Onboard solar panel with battery backup", "One-button operation to transmit GPS location"]', '["Compact and portable â€” easier to carry than a full sensor station", "Sends GPS location directly to SpecConnect platform", "Maps LoRa signal strength and coverage areas", "Solar powered for field use without charging", "Self-contained unit with GPS, LoRa, and power integrated"]', '[]', 'Price on Request', 'INR', true, '0026-06-08 00:23:28+05:53:28', '2026-06-08 00:00:00+05:30', false);
INSERT INTO public.catalogue_products VALUES ('a27ac92c-1bb6-4a72-a381-ce8c34176b37', 'Outdoor Gateway', 'LoRa Gateway', '57c661b5-f9b6-4b31-8781-3ab825b578dd', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', '/product_images/outdoorgateway-1.jpg', '["/product_images/outdoorgateway-2.jpg"]', NULL, 'Outdoor cellular LoRa gateway with 4G LTE-CAT4 connectivity and IP65 weather resistance for wide-area IoT network deployment.', 'The Outdoor LoRa Gateway (4900AS923U) is a reinforced cellular gateway designed for outdoor IoT network infrastructure. Equipped with an internal 4G LTE-CAT4 modem and LoRa radio, it enables wide-area LoRa network connectivity without the need for local Wi-Fi or ethernet. Its IP65-rated enclosure makes it suitable for permanent outdoor installation in all weather conditions, making it ideal for agriculture, smart city, and industrial IoT deployments.', '["LoRa Network Infrastructure", "Smart Agriculture", "Smart City Deployments", "Industrial IoT Connectivity", "Remote Sensor Networks"]', '["Telecommunications", "Agriculture", "Manufacturing", "Smart Cities", "Environmental Monitoring"]', '["Cellular 4G LTE-CAT4 connectivity", "Internal LoRa radio (AS923 frequency)", "IP65 water and dust resistant enclosure", "AC powered for permanent installation"]', '["Outdoor rated for all-weather deployment", "Internal 4G modem - no local network required", "Built-in LoRa radio for wide-area coverage", "Item Number: 4900AS923U", "Reinforced enclosure for permanent mounting"]', '[]', 'Price on Request', 'INR', true, '2026-06-06 00:00:00+05:30', '2026-06-06 00:00:00+05:30', false);
INSERT INTO public.catalogue_products VALUES ('ad0d9ddd-d337-4d0f-86e1-d7bce25e7e03', 'Indoor Gateway', 'Industrial IoT and LoRa Systems', '57c661b5-f9b6-4b31-8781-3ab825b578dd', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', '/product_images/indoorgateway.jpg', '[]', NULL, 'Indoor Ethernet-based LoRa gateway for connecting LoRa nodes to the internet via a wall jack.', 'The Indoor LoRa Gateway (4901AS923) connects to the internet via an available indoor Ethernet port (RJ45), enabling LoRa nodes to transmit data to SpecConnect without cellular connectivity. It requires an AC power source and includes a 50 ft. antenna extension cable for flexible antenna placement indoors.', '["LoRa Network Infrastructure", "Indoor IoT Connectivity", "Smart Agriculture", "Greenhouse Monitoring"]', '["Agriculture", "Horticulture", "Greenhouse", "Research & Academia"]', '["Ethernet RJ45 connectivity", "AC powered for permanent installation", "50 ft. antenna extension cable included", "Item Number: 4901AS923"]', '["Connects via indoor internet wall jack", "No cellular subscription required", "Antenna extension for flexible placement", "Compatible with all LoRa nodes in the WatchDog ecosystem"]', '[]', 'Price on Request', 'INR', true, '2026-06-11 00:00:00+05:30', '2026-06-11 00:00:00+05:30', false);
INSERT INTO public.catalogue_products VALUES ('e4a54042-eace-43a1-99a2-88e7c4d5e8f7', 'LoRa Soil Moisture (2) & (4) VWC/EC/Temp Sensors', 'Soil Moisture Sensor', '57c661b5-f9b6-4b31-8781-3ab825b578dd', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', NULL, '[]', NULL, 'Compact LoRa soil moisture node with 2 or 4 integrated VWC, EC, and temperature sensors for wireless field monitoring.', 'The LoRa Soil Moisture node integrates 2 or 4 VWC/EC/Temp sensors into a single solar-powered unit, transmitting soil condition data wirelessly to SpecConnect via the LoRa network.', '["Soil Moisture Monitoring", "Irrigation Scheduling", "Fertilizer Management", "Precision Agriculture"]', '["Agriculture", "Horticulture", "Research & Academia", "Environmental Monitoring"]', '["2 or 4 VWC/EC/Temp sensor configurations", "Integrated solar panel with rechargeable battery", "LoRa wireless transmission to SpecConnect"]', '["Compact single-unit design with multiple sensors", "Solar powered for field deployment", "Real-time data on SpecConnect platform"]', '[]', 'Price on Request', 'INR', true, '2026-06-11 00:00:00+05:30', '2026-06-11 00:00:00+05:30', true);
INSERT INTO public.catalogue_products VALUES ('cd7c0ba4-7213-4ad9-bd46-71f2c2180250', 'LoRa Temp/RH & Leaf Wetness', 'Environmental Sensor', '57c661b5-f9b6-4b31-8781-3ab825b578dd', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', NULL, '[]', NULL, 'Solar-powered LoRa node measuring temperature, relative humidity, and leaf wetness for crop disease monitoring.', 'The LoRa Temp/RH and Leaf Wetness node combines temperature, relative humidity, and leaf wetness sensing in a single solar-powered unit transmitting data every 5 minutes to SpecConnect via the LoRa network.', '["Crop Disease Monitoring with IPM Software", "Frost and Heat Alerts", "Greenhouse Climate Monitoring", "Leaf Wetness Tracking"]', '["Agriculture", "Horticulture", "Greenhouse", "Environmental Monitoring"]', '["Combined Temp/RH and leaf wetness measurement", "Integrated solar panel with rechargeable battery", "5-minute sampling and transmit interval"]', '["Solar powered for autonomous field deployment", "Real-time alerts via SpecConnect platform", "Suitable for fruit crops, vegetables and greenhouse environments"]', '[]', 'Price on Request', 'INR', true, '2026-06-11 00:00:00+05:30', '2026-06-11 00:00:00+05:30', true);
INSERT INTO public.catalogue_products VALUES ('1cd16141-dbf5-4793-8342-382f5b66a8c8', 'LoRa Rain & Soil Moisture', 'Weather and Soil Sensor', '57c661b5-f9b6-4b31-8781-3ab825b578dd', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', NULL, '[]', NULL, 'Combined LoRa station measuring rainfall and soil moisture with one integrated VWC/EC/Temp sensor.', 'The LoRa Rain and Soil Moisture station combines a rain gauge with one integrated VWC/EC/Temp soil sensor in a single solar-powered unit transmitting data every 5 minutes to SpecConnect via the LoRa network.', '["Rainfall and Soil Moisture Correlation", "Irrigation Scheduling", "Storm Water Management", "Crop Yield Monitoring"]', '["Agriculture", "Horticulture", "Environmental Monitoring", "Research & Academia"]', '["Combined rain gauge and VWC/EC/Temp soil sensor", "Integrated solar panel with rechargeable battery", "5-minute sampling and transmit interval"]', '["Single unit replacing two separate sensors", "Solar powered for autonomous field deployment", "Real-time data correlation of rain and soil moisture"]', '[]', 'Price on Request', 'INR', true, '2026-06-11 00:00:00+05:30', '2026-06-11 00:00:00+05:30', true);
INSERT INTO public.catalogue_products VALUES ('d04fc4a8-2b93-460c-8f0d-55470d8f13dc', 'LoRa Plant Growth (Temp/RH/PAR)', 'Plant Growth Sensor', '57c661b5-f9b6-4b31-8781-3ab825b578dd', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', NULL, '[]', NULL, 'Solar-powered LoRa node measuring temperature, relative humidity, and photosynthetically active radiation for plant growth monitoring.', 'The LoRa Plant Growth node measures temperature, relative humidity, and photosynthetically active radiation (PAR) transmitting data every 5 minutes to SpecConnect via the LoRa network for precise plant growth monitoring.', '["Plant Growth Monitoring", "Greenhouse Climate Optimization", "Photosynthesis Research", "Crop Yield Improvement"]', '["Agriculture", "Greenhouse", "Research & Academia", "Horticulture"]', '["Measures Temp, RH, and PAR (photosynthetically active radiation)", "Integrated solar panel with rechargeable battery", "5-minute sampling and transmit interval"]', '["Covers all three key plant growth parameters in one unit", "Solar powered for autonomous greenhouse deployment", "Real-time PAR and climate data on SpecConnect"]', '[]', 'Price on Request', 'INR', true, '2026-06-11 00:00:00+05:30', '2026-06-11 00:00:00+05:30', true);
INSERT INTO public.catalogue_products VALUES ('5b3e6e82-9247-4ab0-87f0-8ea8478a7e23', 'LoRa Profilers', 'Soil Moisture Probe', 'b08bcaf5-ce11-4008-878e-22c0cae7f7a6', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', '/product_images/loraprofilers-1.jpg', '["/product_images/loraprofilers-2.jpg"]', NULL, 'Multi-depth soil moisture and temperature probe with wireless connectivity for continuous crop monitoring.', 'The multi-depth soil moisture probe integrates multiple soil moisture and temperature sensors into a single probe, spaced every 4 or 8 inches depending on model length. Available in 8 models ranging from 20cm to 100cm, it transmits data every 15 minutes and can be left permanently in the ground for continuous measurement. Data is accessible 24/7 via the WatchDog mobile app, with soil moisture reports showing Volumetric Water Content (VWC) at each sensor depth, making irrigation scheduling significantly easier, especially in arid regions.', '["Irrigation Scheduling", "Soil Moisture Monitoring", "Crop Water Stress Detection", "Precision Agriculture Research"]', '["Agriculture", "Horticulture", "Research & Academia", "Environmental Science"]', '["Multiple moisture and temperature sensors in one probe", "Sensor spacing: every 4 or 8 inches depending on length", "8 models from 20cm to 100cm length", "15-minute sampling and transmit interval"]', '["View data 24/7 on WatchDog mobile app", "VWC reports at each sensor depth", "Permanent in-ground installation for continuous measurement", "Ideal for both permanent and annual crops", "Simplifies irrigation scheduling in arid regions"]', '[]', 'Price on Request', 'INR', true, '2026-06-06 00:00:00+05:30', '2026-06-06 00:00:00+05:30', false);
INSERT INTO public.catalogue_products VALUES ('7b498ad0-437a-481b-9944-0287c90d2a06', 'LoRa Rain/Temp/RH Station', 'Weather Station', 'b08bcaf5-ce11-4008-878e-22c0cae7f7a6', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', '/product_images/loratemp.jpg', '[]', NULL, 'Solar-powered LoRa station measuring rainfall, temperature, and relative humidity with 5-minute transmit intervals.', 'The LoRa Rain/Temp/RH Station is a solar-powered wireless station that measures rainfall, temperature, and relative humidity in the field. With a 5-minute sampling and transmit interval, it delivers real-time weather data to SpecConnect via the LoRa network. The built-in bird guard and quick-assembly design make it easy to deploy across a wide range of agricultural environments.', '["Field-based Rain Data for Crop Yield", "Crop Disease Monitoring with IPM Software", "Field Activity Scheduling on Rainfall Data", "Storm Water Management"]', '["Agriculture", "Horticulture", "Environmental Monitoring", "Research & Academia"]', '["Built-in solar panel for self-powered operation", "Bird guard (spikes) included", "5-minute sampling and transmit interval", "Measures rainfall, temperature, and relative humidity"]', '["Easy, quick assembly for rapid field deployment", "Transmits data to SpecConnect via LoRa network", "Suitable for irrigated row crops, fruit crops, vegetables and row crops", "Solar powered - no external power required"]', '[]', 'Price on Request', 'INR', true, '2026-06-11 00:00:00+05:30', '2026-06-11 00:00:00+05:30', false);
INSERT INTO public.catalogue_products VALUES ('e9a9b97c-9afd-4a0a-ae99-b0ae1c162c24', 'LoRa Rain Station', 'Weather Station', 'b08bcaf5-ce11-4008-878e-22c0cae7f7a6', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', '/product_images/lorarainstation.jpg', '[]', NULL, 'Solar-powered LoRa rain station for field-based rainfall monitoring with 5-minute transmit intervals.', 'The LoRa Rain Station is a dedicated solar-powered rainfall monitoring station designed for agricultural and environmental use. It transmits rainfall data every 5 minutes to SpecConnect via the LoRa network, helping growers schedule field activities, monitor crop yield correlations, and manage storm water. The bird guard and easy-assembly design make it simple to deploy in any field environment.', '["Field-based Rain Data for Crop Yield", "Field Activity Scheduling on Rainfall Data", "Storm Water Management"]', '["Agriculture", "Horticulture", "Environmental Monitoring", "Research & Academia"]', '["Built-in solar panel for self-powered operation", "Bird guard (spikes) included", "5-minute sampling and transmit interval", "Dedicated rainfall measurement"]', '["Easy, quick assembly for rapid field deployment", "Transmits rainfall data to SpecConnect via LoRa", "Suitable for irrigated row crops, fruit crops, vegetables and row crops", "Solar powered - no external power required"]', '[]', 'Price on Request', 'INR', true, '2026-06-11 00:00:00+05:30', '2026-06-11 00:00:00+05:30', false);
INSERT INTO public.catalogue_products VALUES ('1a824370-19ab-46fb-8d03-d8c281dcd830', 'LoRa Temp/RH Sensor', 'Environmental Sensor', 'b08bcaf5-ce11-4008-878e-22c0cae7f7a6', '9e4f0d0d-8bec-4cf3-ae81-4cb21811e200', '/product_images/lorarh.jpg', '[]', NULL, 'Solar-powered LoRa sensor for temperature and relative humidity monitoring with frost and heat alert capabilities.', 'The LoRa Temp/RH Sensor is a compact solar-powered node that monitors temperature and relative humidity in the field, transmitting data every 5 minutes to SpecConnect via the LoRa network. It is ideal for frost and heat alerts, as well as crop disease monitoring using IPM software. Its easy-assembly design allows for quick deployment in greenhouses, orchards, and vegetable fields.', '["Frost Alerts", "Heat Alerts", "Crop Disease Monitoring with IPM Software"]', '["Agriculture", "Horticulture", "Greenhouse", "Environmental Monitoring"]', '["Built-in solar panel for self-powered operation", "5-minute sampling and transmit interval", "Temperature and relative humidity measurement", "Compact node design"]', '["Easy, quick assembly for rapid deployment", "Transmits data to SpecConnect via LoRa network", "Suitable for fruit crops, vegetables and greenhouse environments", "Solar powered - no external power required"]', '[]', 'Price on Request', 'INR', true, '2026-06-11 00:00:00+05:30', '2026-06-11 00:00:00+05:30', false);


--
-- PostgreSQL database dump complete
--

\unrestrict AICL2XgpV4kmYMb4AlGXBJJGR5Nv50wz3hKCcWFgfh3mmn7Ailn3Lkv9FqgqtMl

