import pytest
from httpx import AsyncClient

@pytest.mark.asyncio
async def test_dashboard_summary(client: AsyncClient, admin_auth_headers, seed_organization):
    # 1. Create a tender to populate stats
    payload = {
        "tender_number": "GeM/2026/REPORTS/9999",
        "title": "Cryogenic pump system",
        "organization_id": str(seed_organization.id),
        "tender_value": 500000.00,
        "portal": "GeM",
        "status": "New"
    }
    await client.post("/api/v1/tenders/", json=payload, headers=admin_auth_headers)

    # 2. Query summary statistics
    res = await client.get("/api/v1/reports/summary", headers=admin_auth_headers)
    assert res.status_code == 200
    data = res.json()
    assert data["total_tenders"] == 1
    assert data["total_value"] == 500000.00
    assert data["status_breakdown"]["New"] == 1
    assert data["portal_breakdown"]["GeM"] == 1

@pytest.mark.asyncio
async def test_excel_export(client: AsyncClient, admin_auth_headers):
    # Retrieve Excel sheet download response
    res = await client.get("/api/v1/reports/export", headers=admin_auth_headers)
    assert res.status_code == 200
    assert res.headers["Content-Type"] == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
    assert "attachment" in res.headers["Content-Disposition"]
    assert len(res.content) > 0 # Contains generated bytes

@pytest.mark.asyncio
async def test_email_digest_trigger(client: AsyncClient, admin_auth_headers):
    # Trigger dispatch of email report (uses mock SMTP log fallback)
    payload = {"recipient_email": "digest-recipient@analytica.com"}
    res = await client.post("/api/v1/reports/email", json=payload, headers=admin_auth_headers)
    assert res.status_code == 200
    assert "successfully sent" in res.json()["message"].lower()
