"""init_tip_schema

Revision ID: 0810ff52f420
Revises: 
Create Date: 2026-06-24 14:33:14.066625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0810ff52f420'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('existing_oems', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('product_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=True)
    op.create_table('product_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_providers_name'), 'product_providers', ['name'], unique=False)
    op.create_table('search_keywords',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_keywords_keyword'), 'search_keywords', ['keyword'], unique=True)
    op.create_table('search_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tenders_found', sa.Integer(), nullable=False),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('catalogue_products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('additional_images', sa.JSON(), nullable=False),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('short_description', sa.Text(), nullable=True),
    sa.Column('detailed_description', sa.Text(), nullable=True),
    sa.Column('applications', sa.JSON(), nullable=False),
    sa.Column('industries', sa.JSON(), nullable=False),
    sa.Column('technical_highlights', sa.JSON(), nullable=False),
    sa.Column('key_features', sa.JSON(), nullable=False),
    sa.Column('test_types', sa.JSON(), nullable=False),
    sa.Column('price_range', sa.String(length=255), nullable=False),
    sa.Column('price_currency', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_upcoming', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['product_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogue_products_category_id'), 'catalogue_products', ['category_id'], unique=False)
    op.create_index(op.f('ix_catalogue_products_name'), 'catalogue_products', ['name'], unique=False)
    op.create_index(op.f('ix_catalogue_products_provider_id'), 'catalogue_products', ['provider_id'], unique=False)
    op.create_table('tenders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tender_number', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('department', sa.String(length=500), nullable=True),
    sa.Column('instrument_category', sa.String(length=255), nullable=True),
    sa.Column('portal', sa.String(length=100), nullable=True),
    sa.Column('tender_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('bid_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bid_closing_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('eligible_oems', sa.JSON(), nullable=False),
    sa.Column('existing_oem', sa.String(length=255), nullable=True),
    sa.Column('likely_competitors', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'UNDER_REVIEW', 'INTERESTED', 'BID_SUBMITTED', 'WON', 'LOST', 'CLOSED', name='tenderstatus'), nullable=False),
    sa.Column('action_required', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('document_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_extracted_data', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenders_organization_id'), 'tenders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tenders_tender_number'), 'tenders', ['tender_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenders_tender_number'), table_name='tenders')
    op.drop_index(op.f('ix_tenders_organization_id'), table_name='tenders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_catalogue_products_provider_id'), table_name='catalogue_products')
    op.drop_index(op.f('ix_catalogue_products_name'), table_name='catalogue_products')
    op.drop_index(op.f('ix_catalogue_products_category_id'), table_name='catalogue_products')
    op.drop_table('catalogue_products')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_search_keywords_keyword'), table_name='search_keywords')
    op.drop_table('search_keywords')
    op.drop_index(op.f('ix_product_providers_name'), table_name='product_providers')
    op.drop_table('product_providers')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
